//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.ModeloDeDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoletinBDEntities : DbContext
    {
        public BoletinBDEntities()
            : base("name=BoletinBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_bulletin> tb_bulletin { get; set; }
        public virtual DbSet<tb_grade> tb_grade { get; set; }
        public virtual DbSet<tb_period> tb_period { get; set; }
        public virtual DbSet<tb_student> tb_student { get; set; }
        public virtual DbSet<tb_matter> tb_matter { get; set; }
        public virtual DbSet<tb_result> tb_result { get; set; }
    }
}
