//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bulletin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_bulletin()
        {
            this.tb_matter = new HashSet<tb_matter>();
        }
    
        public int id { get; set; }
        public int id_student { get; set; }
        public int id_grade { get; set; }
        public int id_period { get; set; }
    
        public virtual tb_grade tb_grade { get; set; }
        public virtual tb_period tb_period { get; set; }
        public virtual tb_student tb_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_matter> tb_matter { get; set; }
    }
}
